-- Source reset identity has no login/secret provisioned by this migration.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'o_okul_reset_worker') THEN
    CREATE ROLE o_okul_reset_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
END $$;
CREATE TABLE "TenantFreshResetOperation" (
  "id" text PRIMARY KEY, "tenantId" text NOT NULL REFERENCES "Tenant"("id") ON DELETE RESTRICT,
  "actorUserId" text NOT NULL, "idempotencyKey" text NOT NULL, "requestHash" text NOT NULL,
  "preset" text NOT NULL DEFAULT 'CLEAN_SETUP_V1' CHECK ("preset" = 'CLEAN_SETUP_V1'),
  "expectedLifecycleVersion" integer NOT NULL CHECK ("expectedLifecycleVersion" >= 0),
  "preflightDigest" text NOT NULL, "reason" text NOT NULL CHECK ("reason" IN ('SECURITY_REVIEW','INSTITUTION_REQUEST','OPERATIONS_REVIEW')),
  "status" text NOT NULL DEFAULT 'QUEUED' CHECK ("status" IN ('QUEUED','RUNNING','BLOCKED','FAILED','COMPLETED')),
  "phase" text NOT NULL DEFAULT 'PREFLIGHT' CHECK ("phase" IN ('PREFLIGHT','BACKUP','DATABASE','OBJECTS','VERIFY','DONE')),
  "errorCode" text, "backupReceipt" jsonb, "result" jsonb,
  "createdAt" timestamp(3) NOT NULL DEFAULT now(), "updatedAt" timestamp(3) NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "TenantFreshResetOperation_tenantId_id_key" ON "TenantFreshResetOperation"("tenantId", "id");
CREATE UNIQUE INDEX "TenantFreshResetOperation_actorUserId_idempotencyKey_key" ON "TenantFreshResetOperation"("actorUserId", "idempotencyKey");
CREATE INDEX "TenantFreshResetOperation_tenantId_status_idx" ON "TenantFreshResetOperation"("tenantId", "status");
-- BLOCKED/FAILED retain ownership until this same operation is reconciled.
CREATE UNIQUE INDEX "TenantFreshResetOperation_one_unfinished" ON "TenantFreshResetOperation"("tenantId") WHERE "status" <> 'COMPLETED';
ALTER TABLE "TenantFreshResetOperation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TenantFreshResetOperation" FORCE ROW LEVEL SECURITY;
CREATE POLICY "TenantFreshResetOperation_tenant_isolation" ON "TenantFreshResetOperation"
  USING ("tenantId" = current_setting('app.current_tenant_id', true) OR current_setting('app.bypass_rls', true) = 'true')
  WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) OR current_setting('app.bypass_rls', true) = 'true');
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app') THEN
    GRANT SELECT, INSERT, UPDATE ON "TenantFreshResetOperation" TO app;
    REVOKE DELETE ON "TenantFreshResetOperation" FROM app;
  END IF;
END $$;
GRANT USAGE ON SCHEMA public TO o_okul_reset_worker;
GRANT SELECT ON "TenantFreshResetOperation" TO o_okul_reset_worker;
CREATE POLICY "TenantFreshResetOperation_reset_boundary" ON "TenantFreshResetOperation" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Tenant" TO o_okul_reset_worker;
ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tenant" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Tenant_non_reset_access" ON "Tenant" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "Tenant_reset_access" ON "Tenant" TO o_okul_reset_worker USING ("id" = current_setting('app.current_tenant_id', true) AND "id" <> 'system') WITH CHECK ("id" = current_setting('app.current_tenant_id', true) AND "id" <> 'system');
CREATE POLICY "Tenant_reset_boundary" ON "Tenant" AS RESTRICTIVE TO o_okul_reset_worker USING ("id" = current_setting('app.current_tenant_id', true) AND "id" <> 'system') WITH CHECK ("id" = current_setting('app.current_tenant_id', true) AND "id" <> 'system');
GRANT SELECT ON "LicenseTerm" TO o_okul_reset_worker;
CREATE POLICY "LicenseTerm_reset_boundary" ON "LicenseTerm" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "LicenseUsage" TO o_okul_reset_worker;
CREATE POLICY "LicenseUsage_reset_boundary" ON "LicenseUsage" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AuditLog" TO o_okul_reset_worker;
CREATE POLICY "AuditLog_reset_boundary" ON "AuditLog" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "BackupRestoreJob" TO o_okul_reset_worker;
CREATE POLICY "BackupRestoreJob_reset_boundary" ON "BackupRestoreJob" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ("id") ON "PlatformAccount" TO o_okul_reset_worker;
ALTER TABLE "PlatformAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformAccount" FORCE ROW LEVEL SECURITY;
CREATE POLICY "PlatformAccount_non_reset_access" ON "PlatformAccount" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "PlatformAccount_reset_access" ON "PlatformAccount" TO o_okul_reset_worker USING ("id" IN (SELECT "createdByPlatformAccountId" FROM "LicenseTerm" WHERE "tenantId" = current_setting('app.current_tenant_id', true) UNION SELECT "platformAccountId" FROM "PlatformIdempotencyKey" WHERE "responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true))) WITH CHECK ("id" IN (SELECT "createdByPlatformAccountId" FROM "LicenseTerm" WHERE "tenantId" = current_setting('app.current_tenant_id', true) UNION SELECT "platformAccountId" FROM "PlatformIdempotencyKey" WHERE "responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true)));
CREATE POLICY "PlatformAccount_reset_boundary" ON "PlatformAccount" AS RESTRICTIVE TO o_okul_reset_worker USING ("id" IN (SELECT "createdByPlatformAccountId" FROM "LicenseTerm" WHERE "tenantId" = current_setting('app.current_tenant_id', true) UNION SELECT "platformAccountId" FROM "PlatformIdempotencyKey" WHERE "responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true))) WITH CHECK ("id" IN (SELECT "createdByPlatformAccountId" FROM "LicenseTerm" WHERE "tenantId" = current_setting('app.current_tenant_id', true) UNION SELECT "platformAccountId" FROM "PlatformIdempotencyKey" WHERE "responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true)));
GRANT SELECT ON "PlatformIdempotencyKey" TO o_okul_reset_worker;
ALTER TABLE "PlatformIdempotencyKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformIdempotencyKey" FORCE ROW LEVEL SECURITY;
CREATE POLICY "PlatformIdempotencyKey_non_reset_access" ON "PlatformIdempotencyKey" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "PlatformIdempotencyKey_reset_access" ON "PlatformIdempotencyKey" TO o_okul_reset_worker USING ("responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true)) WITH CHECK ("responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true));
CREATE POLICY "PlatformIdempotencyKey_reset_boundary" ON "PlatformIdempotencyKey" AS RESTRICTIVE TO o_okul_reset_worker USING ("responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true)) WITH CHECK ("responseBody" #>> '{tenant,id}' = current_setting('app.current_tenant_id', true));
GRANT SELECT ON "PlatformSession" TO o_okul_reset_worker;
ALTER TABLE "PlatformSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformSession" FORCE ROW LEVEL SECURITY;
CREATE POLICY "PlatformSession_non_reset_access" ON "PlatformSession" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "PlatformSession_reset_access" ON "PlatformSession" TO o_okul_reset_worker USING (false) WITH CHECK (false);
CREATE POLICY "PlatformSession_reset_boundary" ON "PlatformSession" AS RESTRICTIVE TO o_okul_reset_worker USING (false) WITH CHECK (false);
GRANT SELECT ON "User" TO o_okul_reset_worker;
GRANT DELETE ON "User" TO o_okul_reset_worker;
CREATE POLICY "User_reset_boundary" ON "User" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "TenantMembership" TO o_okul_reset_worker;
GRANT DELETE ON "TenantMembership" TO o_okul_reset_worker;
CREATE POLICY "TenantMembership_reset_boundary" ON "TenantMembership" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Employee" TO o_okul_reset_worker;
GRANT DELETE ON "Employee" TO o_okul_reset_worker;
CREATE POLICY "Employee_reset_boundary" ON "Employee" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "PaymentPlan" TO o_okul_reset_worker;
CREATE POLICY "PaymentPlan_reset_boundary" ON "PaymentPlan" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "PaymentInstallment" TO o_okul_reset_worker;
CREATE POLICY "PaymentInstallment_reset_boundary" ON "PaymentInstallment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "PaymentTransaction" TO o_okul_reset_worker;
CREATE POLICY "PaymentTransaction_reset_boundary" ON "PaymentTransaction" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "SupportTicket" TO o_okul_reset_worker;
CREATE POLICY "SupportTicket_reset_boundary" ON "SupportTicket" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "SupportTicketAttachment" TO o_okul_reset_worker;
CREATE POLICY "SupportTicketAttachment_reset_boundary" ON "SupportTicketAttachment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "SupportTicketComment" TO o_okul_reset_worker;
CREATE POLICY "SupportTicketComment_reset_boundary" ON "SupportTicketComment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "WhatsAppConsent" TO o_okul_reset_worker;
CREATE POLICY "WhatsAppConsent_reset_boundary" ON "WhatsAppConsent" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "WhatsAppConsentEvent" TO o_okul_reset_worker;
CREATE POLICY "WhatsAppConsentEvent_reset_boundary" ON "WhatsAppConsentEvent" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "DevelopmentCriterion" TO o_okul_reset_worker;
GRANT DELETE ON "DevelopmentCriterion" TO o_okul_reset_worker;
CREATE POLICY "DevelopmentCriterion_reset_boundary" ON "DevelopmentCriterion" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "DevelopmentAssessment" TO o_okul_reset_worker;
GRANT DELETE ON "DevelopmentAssessment" TO o_okul_reset_worker;
CREATE POLICY "DevelopmentAssessment_reset_boundary" ON "DevelopmentAssessment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "DevelopmentScore" TO o_okul_reset_worker;
GRANT DELETE ON "DevelopmentScore" TO o_okul_reset_worker;
CREATE POLICY "DevelopmentScore_reset_boundary" ON "DevelopmentScore" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "NotificationDeviceToken" TO o_okul_reset_worker;
GRANT DELETE ON "NotificationDeviceToken" TO o_okul_reset_worker;
CREATE POLICY "NotificationDeviceToken_reset_boundary" ON "NotificationDeviceToken" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "MembershipCampusScope" TO o_okul_reset_worker;
GRANT DELETE ON "MembershipCampusScope" TO o_okul_reset_worker;
CREATE POLICY "MembershipCampusScope_reset_boundary" ON "MembershipCampusScope" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AuthSession" TO o_okul_reset_worker;
GRANT DELETE ON "AuthSession" TO o_okul_reset_worker;
CREATE POLICY "AuthSession_reset_boundary" ON "AuthSession" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "IdempotencyKey" TO o_okul_reset_worker;
GRANT DELETE ON "IdempotencyKey" TO o_okul_reset_worker;
CREATE POLICY "IdempotencyKey_reset_boundary" ON "IdempotencyKey" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "IdentityInvitation" TO o_okul_reset_worker;
GRANT DELETE ON "IdentityInvitation" TO o_okul_reset_worker;
CREATE POLICY "IdentityInvitation_reset_boundary" ON "IdentityInvitation" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ConsumedRefreshToken" TO o_okul_reset_worker;
GRANT DELETE ON "ConsumedRefreshToken" TO o_okul_reset_worker;
ALTER TABLE "ConsumedRefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConsumedRefreshToken" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ConsumedRefreshToken_non_reset_access" ON "ConsumedRefreshToken" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "ConsumedRefreshToken_reset_access" ON "ConsumedRefreshToken" TO o_okul_reset_worker USING ("tokenFamilyId" IN (SELECT "tokenFamilyId" FROM "AuthSession" WHERE "tenantId" = current_setting('app.current_tenant_id', true))) WITH CHECK ("tokenFamilyId" IN (SELECT "tokenFamilyId" FROM "AuthSession" WHERE "tenantId" = current_setting('app.current_tenant_id', true)));
CREATE POLICY "ConsumedRefreshToken_reset_boundary" ON "ConsumedRefreshToken" AS RESTRICTIVE TO o_okul_reset_worker USING ("tokenFamilyId" IN (SELECT "tokenFamilyId" FROM "AuthSession" WHERE "tenantId" = current_setting('app.current_tenant_id', true))) WITH CHECK ("tokenFamilyId" IN (SELECT "tokenFamilyId" FROM "AuthSession" WHERE "tenantId" = current_setting('app.current_tenant_id', true)));
GRANT SELECT ON "PasswordResetToken" TO o_okul_reset_worker;
GRANT DELETE ON "PasswordResetToken" TO o_okul_reset_worker;
ALTER TABLE "PasswordResetToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PasswordResetToken" FORCE ROW LEVEL SECURITY;
CREATE POLICY "PasswordResetToken_non_reset_access" ON "PasswordResetToken" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "PasswordResetToken_reset_access" ON "PasswordResetToken" TO o_okul_reset_worker USING ("userId" IN (SELECT "id" FROM "User" WHERE "tenantId" = current_setting('app.current_tenant_id', true))) WITH CHECK ("userId" IN (SELECT "id" FROM "User" WHERE "tenantId" = current_setting('app.current_tenant_id', true)));
CREATE POLICY "PasswordResetToken_reset_boundary" ON "PasswordResetToken" AS RESTRICTIVE TO o_okul_reset_worker USING ("userId" IN (SELECT "id" FROM "User" WHERE "tenantId" = current_setting('app.current_tenant_id', true))) WITH CHECK ("userId" IN (SELECT "id" FROM "User" WHERE "tenantId" = current_setting('app.current_tenant_id', true)));
GRANT SELECT ON "SecretDeliveryOutbox" TO o_okul_reset_worker;
GRANT DELETE ON "SecretDeliveryOutbox" TO o_okul_reset_worker;
ALTER TABLE "SecretDeliveryOutbox" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SecretDeliveryOutbox" FORCE ROW LEVEL SECURITY;
CREATE POLICY "SecretDeliveryOutbox_non_reset_access" ON "SecretDeliveryOutbox" USING (current_user <> 'o_okul_reset_worker') WITH CHECK (current_user <> 'o_okul_reset_worker');
CREATE POLICY "SecretDeliveryOutbox_reset_access" ON "SecretDeliveryOutbox" TO o_okul_reset_worker USING ((("tenantId" IS NULL OR "tenantId" = current_setting('app.current_tenant_id', true)) AND (("purpose" = 'PASSWORD_RESET' AND "sourceId" IN (SELECT "id" FROM "PasswordResetToken")) OR ("purpose" = 'IDENTITY_INVITATION' AND "sourceId" IN (SELECT "id" FROM "IdentityInvitation"))))) WITH CHECK ((("tenantId" IS NULL OR "tenantId" = current_setting('app.current_tenant_id', true)) AND (("purpose" = 'PASSWORD_RESET' AND "sourceId" IN (SELECT "id" FROM "PasswordResetToken")) OR ("purpose" = 'IDENTITY_INVITATION' AND "sourceId" IN (SELECT "id" FROM "IdentityInvitation")))));
CREATE POLICY "SecretDeliveryOutbox_reset_boundary" ON "SecretDeliveryOutbox" AS RESTRICTIVE TO o_okul_reset_worker USING ((("tenantId" IS NULL OR "tenantId" = current_setting('app.current_tenant_id', true)) AND (("purpose" = 'PASSWORD_RESET' AND "sourceId" IN (SELECT "id" FROM "PasswordResetToken")) OR ("purpose" = 'IDENTITY_INVITATION' AND "sourceId" IN (SELECT "id" FROM "IdentityInvitation"))))) WITH CHECK ((("tenantId" IS NULL OR "tenantId" = current_setting('app.current_tenant_id', true)) AND (("purpose" = 'PASSWORD_RESET' AND "sourceId" IN (SELECT "id" FROM "PasswordResetToken")) OR ("purpose" = 'IDENTITY_INVITATION' AND "sourceId" IN (SELECT "id" FROM "IdentityInvitation")))));
GRANT SELECT ON "Class" TO o_okul_reset_worker;
GRANT DELETE ON "Class" TO o_okul_reset_worker;
CREATE POLICY "Class_reset_boundary" ON "Class" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "GradeLevel" TO o_okul_reset_worker;
GRANT DELETE ON "GradeLevel" TO o_okul_reset_worker;
CREATE POLICY "GradeLevel_reset_boundary" ON "GradeLevel" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Alan" TO o_okul_reset_worker;
GRANT DELETE ON "Alan" TO o_okul_reset_worker;
CREATE POLICY "Alan_reset_boundary" ON "Alan" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Campus" TO o_okul_reset_worker;
GRANT DELETE ON "Campus" TO o_okul_reset_worker;
CREATE POLICY "Campus_reset_boundary" ON "Campus" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Course" TO o_okul_reset_worker;
GRANT DELETE ON "Course" TO o_okul_reset_worker;
CREATE POLICY "Course_reset_boundary" ON "Course" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "GradeLevelCourse" TO o_okul_reset_worker;
GRANT DELETE ON "GradeLevelCourse" TO o_okul_reset_worker;
CREATE POLICY "GradeLevelCourse_reset_boundary" ON "GradeLevelCourse" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AcademicYear" TO o_okul_reset_worker;
GRANT DELETE ON "AcademicYear" TO o_okul_reset_worker;
CREATE POLICY "AcademicYear_reset_boundary" ON "AcademicYear" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AcademicTerm" TO o_okul_reset_worker;
GRANT DELETE ON "AcademicTerm" TO o_okul_reset_worker;
CREATE POLICY "AcademicTerm_reset_boundary" ON "AcademicTerm" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Student" TO o_okul_reset_worker;
GRANT DELETE ON "Student" TO o_okul_reset_worker;
CREATE POLICY "Student_reset_boundary" ON "Student" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "StudentEnrollment" TO o_okul_reset_worker;
GRANT DELETE ON "StudentEnrollment" TO o_okul_reset_worker;
CREATE POLICY "StudentEnrollment_reset_boundary" ON "StudentEnrollment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Teacher" TO o_okul_reset_worker;
GRANT DELETE ON "Teacher" TO o_okul_reset_worker;
CREATE POLICY "Teacher_reset_boundary" ON "Teacher" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "StudentContact" TO o_okul_reset_worker;
GRANT DELETE ON "StudentContact" TO o_okul_reset_worker;
CREATE POLICY "StudentContact_reset_boundary" ON "StudentContact" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "TeacherAssignment" TO o_okul_reset_worker;
GRANT DELETE ON "TeacherAssignment" TO o_okul_reset_worker;
CREATE POLICY "TeacherAssignment_reset_boundary" ON "TeacherAssignment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Guardian" TO o_okul_reset_worker;
GRANT DELETE ON "Guardian" TO o_okul_reset_worker;
CREATE POLICY "Guardian_reset_boundary" ON "Guardian" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "GuardianStudent" TO o_okul_reset_worker;
GRANT DELETE ON "GuardianStudent" TO o_okul_reset_worker;
CREATE POLICY "GuardianStudent_reset_boundary" ON "GuardianStudent" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Attendance" TO o_okul_reset_worker;
GRANT DELETE ON "Attendance" TO o_okul_reset_worker;
CREATE POLICY "Attendance_reset_boundary" ON "Attendance" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "TeacherNote" TO o_okul_reset_worker;
GRANT DELETE ON "TeacherNote" TO o_okul_reset_worker;
CREATE POLICY "TeacherNote_reset_boundary" ON "TeacherNote" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ScheduleLesson" TO o_okul_reset_worker;
GRANT DELETE ON "ScheduleLesson" TO o_okul_reset_worker;
CREATE POLICY "ScheduleLesson_reset_boundary" ON "ScheduleLesson" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "StudySession" TO o_okul_reset_worker;
GRANT DELETE ON "StudySession" TO o_okul_reset_worker;
CREATE POLICY "StudySession_reset_boundary" ON "StudySession" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "StudySessionStudent" TO o_okul_reset_worker;
GRANT DELETE ON "StudySessionStudent" TO o_okul_reset_worker;
CREATE POLICY "StudySessionStudent_reset_boundary" ON "StudySessionStudent" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "HomeworkMaterial" TO o_okul_reset_worker;
GRANT DELETE ON "HomeworkMaterial" TO o_okul_reset_worker;
CREATE POLICY "HomeworkMaterial_reset_boundary" ON "HomeworkMaterial" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "HomeworkMaterialFile" TO o_okul_reset_worker;
GRANT DELETE ON "HomeworkMaterialFile" TO o_okul_reset_worker;
CREATE POLICY "HomeworkMaterialFile_reset_boundary" ON "HomeworkMaterialFile" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "HomeworkMaterialAssignment" TO o_okul_reset_worker;
GRANT DELETE ON "HomeworkMaterialAssignment" TO o_okul_reset_worker;
CREATE POLICY "HomeworkMaterialAssignment_reset_boundary" ON "HomeworkMaterialAssignment" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Homework" TO o_okul_reset_worker;
GRANT DELETE ON "Homework" TO o_okul_reset_worker;
CREATE POLICY "Homework_reset_boundary" ON "Homework" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Exam" TO o_okul_reset_worker;
GRANT DELETE ON "Exam" TO o_okul_reset_worker;
CREATE POLICY "Exam_reset_boundary" ON "Exam" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ParserConfig" TO o_okul_reset_worker;
GRANT DELETE ON "ParserConfig" TO o_okul_reset_worker;
CREATE POLICY "ParserConfig_reset_boundary" ON "ParserConfig" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "OpticalFormTemplate" TO o_okul_reset_worker;
GRANT DELETE ON "OpticalFormTemplate" TO o_okul_reset_worker;
CREATE POLICY "OpticalFormTemplate_reset_boundary" ON "OpticalFormTemplate" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ExamParticipant" TO o_okul_reset_worker;
GRANT DELETE ON "ExamParticipant" TO o_okul_reset_worker;
CREATE POLICY "ExamParticipant_reset_boundary" ON "ExamParticipant" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "RawImport" TO o_okul_reset_worker;
GRANT DELETE ON "RawImport" TO o_okul_reset_worker;
CREATE POLICY "RawImport_reset_boundary" ON "RawImport" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AnswerKey" TO o_okul_reset_worker;
GRANT DELETE ON "AnswerKey" TO o_okul_reset_worker;
CREATE POLICY "AnswerKey_reset_boundary" ON "AnswerKey" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ExamBookletVariant" TO o_okul_reset_worker;
GRANT DELETE ON "ExamBookletVariant" TO o_okul_reset_worker;
CREATE POLICY "ExamBookletVariant_reset_boundary" ON "ExamBookletVariant" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "LearningOutcome" TO o_okul_reset_worker;
GRANT DELETE ON "LearningOutcome" TO o_okul_reset_worker;
CREATE POLICY "LearningOutcome_reset_boundary" ON "LearningOutcome" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ParsedAnswer" TO o_okul_reset_worker;
GRANT DELETE ON "ParsedAnswer" TO o_okul_reset_worker;
CREATE POLICY "ParsedAnswer_reset_boundary" ON "ParsedAnswer" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ExamResult" TO o_okul_reset_worker;
GRANT DELETE ON "ExamResult" TO o_okul_reset_worker;
CREATE POLICY "ExamResult_reset_boundary" ON "ExamResult" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ImportQuarantine" TO o_okul_reset_worker;
GRANT DELETE ON "ImportQuarantine" TO o_okul_reset_worker;
CREATE POLICY "ImportQuarantine_reset_boundary" ON "ImportQuarantine" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "ReportSnapshot" TO o_okul_reset_worker;
GRANT DELETE ON "ReportSnapshot" TO o_okul_reset_worker;
CREATE POLICY "ReportSnapshot_reset_boundary" ON "ReportSnapshot" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "Announcement" TO o_okul_reset_worker;
GRANT DELETE ON "Announcement" TO o_okul_reset_worker;
CREATE POLICY "Announcement_reset_boundary" ON "Announcement" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AnnouncementReceipt" TO o_okul_reset_worker;
GRANT DELETE ON "AnnouncementReceipt" TO o_okul_reset_worker;
CREATE POLICY "AnnouncementReceipt_reset_boundary" ON "AnnouncementReceipt" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "AnnouncementDeliveryReport" TO o_okul_reset_worker;
GRANT DELETE ON "AnnouncementDeliveryReport" TO o_okul_reset_worker;
CREATE POLICY "AnnouncementDeliveryReport_reset_boundary" ON "AnnouncementDeliveryReport" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "MessageTemplate" TO o_okul_reset_worker;
GRANT DELETE ON "MessageTemplate" TO o_okul_reset_worker;
CREATE POLICY "MessageTemplate_reset_boundary" ON "MessageTemplate" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "SmsBatchDeliveryReport" TO o_okul_reset_worker;
GRANT DELETE ON "SmsBatchDeliveryReport" TO o_okul_reset_worker;
CREATE POLICY "SmsBatchDeliveryReport_reset_boundary" ON "SmsBatchDeliveryReport" AS RESTRICTIVE TO o_okul_reset_worker USING ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system') WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true) AND "tenantId" <> 'system');
GRANT SELECT ON "_prisma_migrations" TO o_okul_reset_worker;
GRANT UPDATE ("status", "lifecycleVersion", "suspendedAt", "suspendedReason", "updatedAt") ON "Tenant" TO o_okul_reset_worker;
GRANT UPDATE ("mustChangePassword", "membershipVersion", "updatedAt") ON "User" TO o_okul_reset_worker;
GRANT UPDATE ("role", "staffRole", "scopeMode", "hasTeacherPersona", "hasStudentPersona", "version", "updatedAt") ON "TenantMembership" TO o_okul_reset_worker;
GRANT UPDATE ("linkedTytExamId") ON "Exam" TO o_okul_reset_worker;
GRANT UPDATE ("status", "phase", "errorCode", "backupReceipt", "result", "updatedAt") ON "TenantFreshResetOperation" TO o_okul_reset_worker;
GRANT INSERT ON "AuditLog" TO o_okul_reset_worker;
REVOKE DELETE ON "Tenant", "AuditLog", "TenantFreshResetOperation", "LicenseTerm", "LicenseUsage" FROM o_okul_reset_worker;

CREATE FUNCTION o_okul_block_active_during_reset() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."status" = 'ACTIVE' AND OLD."status" <> 'ACTIVE' AND EXISTS (
    SELECT 1 FROM "TenantFreshResetOperation" WHERE "tenantId" = NEW."id" AND "status" <> 'COMPLETED'
  ) THEN RAISE EXCEPTION USING MESSAGE = 'RESET_OPERATION_IN_PROGRESS'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER "Tenant_block_active_during_reset" BEFORE UPDATE OF "status" ON "Tenant"
FOR EACH ROW EXECUTE FUNCTION o_okul_block_active_during_reset();
